# Generated by Django 4.2.18 on 2025-03-22 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haki_flg', models.IntegerField(default=0)),
                ('item_nm', models.TextField()),
                ('group_id', models.CharField(max_length=10)),
                ('purchaser_nm', models.CharField(max_length=100)),
                ('evaluation', models.IntegerField()),
                ('review_title', models.CharField(blank=True, max_length=100, null=True)),
                ('review_text', models.TextField()),
                ('sex', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=10)),
                ('item_detail', models.CharField(max_length=100)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'T_REVIEW',
                'indexes': [models.Index(fields=['item_nm'], name='T_REVIEW_item_nm_033567_idx'), models.Index(fields=['review_text'], name='T_REVIEW_review__7f3bc3_idx')],
            },
        ),
    ]
